# Dependabot configuration file
# See documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # Specifies Go modules
    directory: "/" # Location of go.mod file
    schedule:
      interval: "weekly" # Check for updates once a week
    open-pull-requests-limit: 10 # Limit number of open PRs
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "go mod"
      include: "scope"

  - package-ecosystem: "github-actions" # GitHub Actions workflows
    directory: "/" # Location of workflow files in .github/workflows
    schedule:
      interval: "weekly" # Check for updates once a week
    open-pull-requests-limit: 5 # Limit number of open PRs
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "npm" # npm packages for web UI
    directory: "/web" # Location of package.json file
    schedule:
      interval: "daily" # Check for updates once a day
    open-pull-requests-limit: 10 # Limit number of open PRs
    labels:
      - "dependencies"
      - "npm"
      - "web-ui"
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      testing-library:
        patterns:
          - "@testing-library/*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "tailwindcss-animate"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "typescript-eslint"
          - "eslint-plugin-*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vitest"
      postcss:
        patterns:
          - "postcss"
          - "autofixer"
    ignore:
      - dependency-name: "rollup"
        versions: ["4.46.0", "4.46.1", "4.46.2"]
    commit-message:
      prefix: "npm"
      include: "scope"
