name: Go Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Run tests when Dependabot creates PRs
  pull_request_target:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # You can adjust this to match your project's Go version

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
